/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <rpc/rpc.h>
#include <stdio.h>
#include "file.h"

int main (int argc, char *argv[])
{
	char *host;
	char operazione[10];

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	CLIENT *clnt;
	RisultatoConteggio  *result_1;
	File  file_scan_1_arg;
	OutputDirScan  *result_2;
	InputDirScan  dir_scan_1_arg;
	char soglia[10];
	
	clnt = clnt_create (host, FILEPROG, FILEVERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	
	printf("inserisci l'operazione(f/d): ");
    while( gets(operazione) )  {
		if( operazione[0] == 'f' ) {
			//file_scan()
			printf("inserisci il nome del file su cui eseguire file_scan: ");
			gets(file_scan_1_arg.nomeFile);
			
			result_1 = file_scan_1(&file_scan_1_arg, clnt);
			if (result_1 == (RisultatoConteggio *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			
			printf("il risultato del conteggio: %d linee; %d parole; %d caratteri\n", result_1->numRighe, result_1->numParole, result_1->numCaratteri); 
		}
		else if( operazione[0] == 'd' ) {
			//dirscan()
			printf("inserisci il nome della directory  su cui eseguire dir_scan: ");
			gets(dir_scan_1_arg.dir.nomeFile);
			printf("inserisci la soglia con cui eseguire dir_scan: ");
			gets(soglia);
			dir_scan_1_arg.soglia = atoi(soglia);

			printf("dir: %s; soglia: %d\n", dir_scan_1_arg.dir.nomeFile, dir_scan_1_arg.soglia);

			
			result_2 = dir_scan_1(&dir_scan_1_arg, clnt);
			if (result_2 == (OutputDirScan *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			
			printf("il risultato della dirscan: %d file sopra soglia\n", result_2->numerosita); 
			if( result_2->numerosita > 0 ) {
				printf("nomi file: \n");
				for(int i = 0; i < result_2->numerosita; i++ ) {
					printf("\t%s\n", result_2->fileSopraSoglia.files[i].nomeFile); 
				}
			}
		}
		else{
			printf("operazione invalida"); 
		}

		printf("inserisci l'operazione(f/d): ");
	}


	clnt_destroy(clnt);

	exit(0);
}
