/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file.h"

bool_t
xdr_File (XDR *xdrs, File *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomeFile, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RisultatoConteggio (XDR *xdrs, RisultatoConteggio *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numRighe))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numParole))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numCaratteri))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InputDirScan (XDR *xdrs, InputDirScan *objp)
{
	register int32_t *buf;

	 if (!xdr_File (xdrs, &objp->dir))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->soglia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FileSopraSoglia (XDR *xdrs, FileSopraSoglia *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->files, 8,
		sizeof (File), (xdrproc_t) xdr_File))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputDirScan (XDR *xdrs, OutputDirScan *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numerosita))
		 return FALSE;
	 if (!xdr_FileSopraSoglia (xdrs, &objp->fileSopraSoglia))
		 return FALSE;
	return TRUE;
}
