/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fattorex.h"


void
fattorex_1(char *host)
{
	CLIENT *clnt;
	classifica_giudici  *result_1;
	char *visualizza_classifica_1_arg;
	void  *result_2;
	char  aggiungi_voto_1_arg;
	void  *result_3;
	char  rimuovi_voto_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FATTOREX, FATTOREXVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = visualizza_classifica_1((void*)&visualizza_classifica_1_arg, clnt);
	if (result_1 == (classifica_giudici *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = aggiungi_voto_1(&aggiungi_voto_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = rimuovi_voto_1(&rimuovi_voto_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fattorex_1 (host);
exit (0);
}
