/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fattorex.h"



classifica_giudici *
visualizza_classifica_1_svc(void *argp, struct svc_req *rqstp)
{
	static classifica_giudici result;
	int i, j;

	//scorro la matrice
	for (i = 0; i < NUM_CANDIDATI; i++) {
		//controllo che il giudice sia nuovo scorrendo tutte le entry del risultato
		for(j = 0; j < NUM_CANDIDATI; j++) {
			//giudice gia presente -> sommo i voti
			if( strcmp( matrice.riga[i].giudice, result.classifica[j].name) == 0 ) {
				result.classifica[j].num_voti += matrice.riga[i].voti;
			}
			//giudice nuovo -> aggiungo al risultato
			else{
				result.classifica
			}
		} 

	 	

    }

	return &result;
}

void *
aggiungi_voto_1_svc(char *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

void *
rimuovi_voto_1_svc(char *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
