/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fattorex.h"

static MATRICE matrice;	
static int inizializzato=0;

void inizializza() {
    int i;

    // inizializzazione struttura dati
    for (i = 0; i < NUM_CANDIDATI; i++) {
        strcpy(matrice.riga[i].candidato, "L");
        strcpy(matrice.riga[i].giudice, "L");
		matrice.riga[i].categoria = 'L';
		strcpy(matrice.riga[i].nomeFile, "L");
		matrice.riga[i].fase = 'L';
		matrice.riga[i].voti = -1;
    }

	//riga 1
	strcpy(matrice.riga[0].candidato, "Koltraka Kevin");
	strcpy(matrice.riga[0].giudice, "Maria de Filippi");
	matrice.riga[0].categoria = 'U';
	strcpy(matrice.riga[0].nomeFile, "kevin.txt");
	matrice.riga[0].fase = 'S';
	matrice.riga[0].voti = 236;
	//riga 2
	strcpy(matrice.riga[1].candidato, "Francesco Roffia");
	strcpy(matrice.riga[1].giudice, "Paul Mcartney");
	matrice.riga[1].categoria = 'O';
	strcpy(matrice.riga[1].nomeFile, "frank.txt");
	matrice.riga[1].fase = 'A';
	matrice.riga[1].voti = 2252;
	//riga 7
	strcpy(matrice.riga[6].candidato, "Mario Rossi");
	strcpy(matrice.riga[6].giudice, "Paul Mcartney");
	matrice.riga[6].categoria = 'B';
	strcpy(matrice.riga[6].nomeFile, "mario.txt");
	matrice.riga[6].fase = 'B';
	matrice.riga[6].voti = 12;

    printf("Terminata inizializzazione struttura dati!\n");
	inizializzato=1;
}

classifica_giudici *
visualizza_classifica_1_svc(void *argp, struct svc_req *rqstp) {

	if(inizializzato==0) {
		inizializza();
		//stampa di debug
		int i;
		for (i = 0; i < NUM_CANDIDATI; i++) {
			printf("%s; ", matrice.riga[i].candidato );
			printf("%s; ", matrice.riga[i].giudice );
			printf("%c; ", matrice.riga[i].categoria  );
			printf("%s; ", matrice.riga[i].nomeFile  );
			printf("%c; ", matrice.riga[i].fase );
			printf("%d;\n", matrice.riga[i].voti  );
		}
	}

	static classifica_giudici result;
	int i, j;
	int trovato=0;

	//inizializzazione risultato
	result.num_giudici=0;

	printf("richiesta di visualizzazione classifica ricevuta\n");

	//scorro la matrice
	// for (i=0; i<NUM_CANDIDATI; i++) {
	// 	//controllo che il giudice sia nuovo scorrendo tutte le entry del risultato
	// 	for(j=0; j<result.num_giudici && !trovato; j++) {
	// 		//giudice gia presente -> sommo i voti
	// 		if( strcmp( matrice.riga[i].giudice, result.classifica[j].name) == 0 ) {
	// 			result.classifica[j].num_voti += matrice.riga[i].voti;
	// 			trovato=1;
	// 		}
	// 	} 

	// 	if(!trovato) {
	// 		//non ho trovato il giudice -> aggiungo una nuova entry al risultato
	// 		strcpy(result.classifica[result.num_giudici].name, matrice.riga[i].giudice);
	// 		result.classifica[result.num_giudici].num_voti = matrice.riga[i].voti;
	// 		result.num_giudici++;
	// 	}
	 	
	// 	trovato=0;
    // }

	//TODO: ordina il risultato


	strcpy(result.classifica[0].name, matrice.riga[0].giudice);
	result.classifica[0].num_voti = matrice.riga[0].voti;
	result.num_giudici++;
	
	strcpy(result.classifica[1].name, matrice.riga[1].giudice);
	result.classifica[1].num_voti = matrice.riga[1].voti;
	result.num_giudici++;
	//stampa classifica
	for(i=0; i<result.num_giudici; i++) {
		printf("Giudice %s: %d voti\n", result.classifica[i].name, result.classifica[i].num_voti );
	}

	return &result;
}

void *
aggiungi_voto_1_svc(char *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

void *
rimuovi_voto_1_svc(char *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
