/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
operation_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		input_espressione_voto esprimi_voto_1_arg;
		candidato_entry aggiungi_candidato_1_arg;
		nametype rimuovi_candidato_1_arg;
		char get_candidati_of_fase_1_arg;
		char get_candidati_of_categoria_1_arg;
		int get_candidati_with_voti_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case CLASSIFICA_GIUDICI:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_classifica_giudici;
		local = (char *(*)(char *, struct svc_req *)) classifica_giudici_1_svc;
		break;

	case ESPRIMI_VOTO:
		_xdr_argument = (xdrproc_t) xdr_input_espressione_voto;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) esprimi_voto_1_svc;
		break;

	case VISUALIZZA_CANDIDATI:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_candidati_list;
		local = (char *(*)(char *, struct svc_req *)) visualizza_candidati_1_svc;
		break;

	case AGGIUNGI_CANDIDATO:
		_xdr_argument = (xdrproc_t) xdr_candidato_entry;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) aggiungi_candidato_1_svc;
		break;

	case RIMUOVI_CANDIDATO:
		_xdr_argument = (xdrproc_t) xdr_nametype;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rimuovi_candidato_1_svc;
		break;

	case GET_CANDIDATI_OF_FASE:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_candidati_list;
		local = (char *(*)(char *, struct svc_req *)) get_candidati_of_fase_1_svc;
		break;

	case GET_CANDIDATI_OF_CATEGORIA:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_candidati_list;
		local = (char *(*)(char *, struct svc_req *)) get_candidati_of_categoria_1_svc;
		break;

	case GET_CANDIDATI_WITH_VOTI:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_candidati_list;
		local = (char *(*)(char *, struct svc_req *)) get_candidati_with_voti_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

/* dichiarazione metodo di inizializzione */
void inizializza();

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (OPERATION, OPERATIONVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, OPERATION, OPERATIONVERS, operation_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (OPERATION, OPERATIONVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OPERATION, OPERATIONVERS, operation_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OPERATION, OPERATIONVERS, tcp).");
		exit(1);
	}

	inizializza();

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
