/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "xfactor.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

classifica_giudici *
classifica_giudici_1(void *argp, CLIENT *clnt)
{
	static classifica_giudici clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CLASSIFICA_GIUDICI,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_classifica_giudici, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
esprimi_voto_1(input_espressione_voto *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ESPRIMI_VOTO,
		(xdrproc_t) xdr_input_espressione_voto, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

candidati_list *
visualizza_candidati_1(void *argp, CLIENT *clnt)
{
	static candidati_list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, VISUALIZZA_CANDIDATI,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_candidati_list, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
aggiungi_candidato_1(candidato_entry *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, AGGIUNGI_CANDIDATO,
		(xdrproc_t) xdr_candidato_entry, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
rimuovi_candidato_1(nametype *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RIMUOVI_CANDIDATO,
		(xdrproc_t) xdr_nametype, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

candidati_list *
get_candidati_of_fase_1(char *argp, CLIENT *clnt)
{
	static candidati_list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_CANDIDATI_OF_FASE,
		(xdrproc_t) xdr_char, (caddr_t) argp,
		(xdrproc_t) xdr_candidati_list, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

candidati_list *
get_candidati_of_categoria_1(char *argp, CLIENT *clnt)
{
	static candidati_list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_CANDIDATI_OF_CATEGORIA,
		(xdrproc_t) xdr_char, (caddr_t) argp,
		(xdrproc_t) xdr_candidati_list, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

candidati_list *
get_candidati_with_voti_1(int *argp, CLIENT *clnt)
{
	static candidati_list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_CANDIDATI_WITH_VOTI,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_candidati_list, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
