/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "xfactor.h"


void
operation_1(char *host)
{
	CLIENT *clnt;
	Output  *result_1;
	char *classifica_giudici_1_arg;
	int  *result_2;
	Input  esprimi_voto_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OPERATION, OPERATIONVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = classifica_giudici_1((void*)&classifica_giudici_1_arg, clnt);
	if (result_1 == (Output *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = esprimi_voto_1(&esprimi_voto_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	//client	
	char operazione[10];
	int i;
	CLIENT *clnt;
	Output  *result_1;
	char *classifica_giudici_1_arg;	//parametro finto
	int  *result_2;
	Input  esprimi_voto_1_arg;
	char ok[255];

	clnt = clnt_create (host, OPERATION, OPERATIONVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	printf("inserisci l'operazione desiderata(V=visualizza classifica, E=esprimi un voto):");
	while( gets(operazione) ) {
		//visualizza classifica
		if(operazione[0] == 'V') {
			result_1 = classifica_giudici_1((void*)&classifica_giudici_1_arg, clnt);
			if (result_1 == (Output *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			//stampa classifica
			for(i=0; i< NUM_GIUDICI; i++) {
				//faccio così perchè non ho accoppiato al vettore risultato la dimensione effettiva
				if(strcmp(result_1->classificaGiudici[i].nomeGiudice, "L") == 0)
					break;

				printf("Giudice: %s; %d voti\n", result_1->classificaGiudici[i].nomeGiudice, result_1->classificaGiudici[i].punteggioTot );
			}
		}
		//esprimi un voto
		else if(operazione[0] == 'E') {
			printf("inserisci il nome del candidato da votare: ");
			gets(esprimi_voto_1_arg.nomeCandidato);
			printf("a/r?: ");
			scanf("%c", &esprimi_voto_1_arg.tipoOp);
			//elimino il fine riga
			gets(ok);

			result_2 = esprimi_voto_1(&esprimi_voto_1_arg, clnt);
			if (result_2 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			if(*result_2 == -1) {
				printf("errore, candidato inserito non presente\n");
			}
			if(*result_2 == -2) {
				printf("errore, tipo di voto non ammesso(a/r)\n");
			}
		}
 		else{
			printf("operazione non supportata!\n");
		}

		printf("inserisci l'operazione desiderata(V=visualizza classifica, E=esprimi un voto):");
	}
	
	clnt_destroy (clnt);


	exit (0);
}
