/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "NoleggiaSci.h"

bool_t
xdr_entry (XDR *xdrs, entry *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->id, STRING_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, DATA_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->giorni_noleggio))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->modello, STRING_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costo_giornaliero))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nome_file_foto, FILE_NAME_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_noleggi (XDR *xdrs, noleggi *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->noleggio, MAX_NOLEGGI,
		sizeof (entry), (xdrproc_t) xdr_entry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input_elimina_sci (XDR *xdrs, input_elimina_sci *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->id, STRING_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input_noleggia_sci (XDR *xdrs, input_noleggia_sci *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->id, STRING_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, DATA_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->giorni_noleggio))
		 return FALSE;
	return TRUE;
}
