/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NOLEGGIASCI_H_RPCGEN
#define _NOLEGGIASCI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define FILE_NAME_DIM 50
#define STRING_DIM 50
#define DATA_DIM 11
#define MAX_NOLEGGI 100

struct entry {
	char id[STRING_DIM];
	char data[DATA_DIM];
	int giorni_noleggio;
	char modello[STRING_DIM];
	float costo_giornaliero;
	char nome_file_foto[FILE_NAME_DIM];
};
typedef struct entry entry;

struct noleggi {
	entry noleggio[MAX_NOLEGGI];
};
typedef struct noleggi noleggi;

struct input_elimina_sci {
	char id[STRING_DIM];
};
typedef struct input_elimina_sci input_elimina_sci;

struct input_noleggia_sci {
	char id[STRING_DIM];
	char data[DATA_DIM];
	int giorni_noleggio;
};
typedef struct input_noleggia_sci input_noleggia_sci;

#define NOLEGGIA_SCI 0x20000013
#define NOLEGGIA_SCI_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ELIMINA_SCI 1
extern  int * elimina_sci_1(input_elimina_sci *, CLIENT *);
extern  int * elimina_sci_1_svc(input_elimina_sci *, struct svc_req *);
#define NOLEGGIO_SCI 2
extern  int * noleggio_sci_1(input_noleggia_sci *, CLIENT *);
extern  int * noleggio_sci_1_svc(input_noleggia_sci *, struct svc_req *);
extern int noleggia_sci_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ELIMINA_SCI 1
extern  int * elimina_sci_1();
extern  int * elimina_sci_1_svc();
#define NOLEGGIO_SCI 2
extern  int * noleggio_sci_1();
extern  int * noleggio_sci_1_svc();
extern int noleggia_sci_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entry (XDR *, entry*);
extern  bool_t xdr_noleggi (XDR *, noleggi*);
extern  bool_t xdr_input_elimina_sci (XDR *, input_elimina_sci*);
extern  bool_t xdr_input_noleggia_sci (XDR *, input_noleggia_sci*);

#else /* K&R C */
extern bool_t xdr_entry ();
extern bool_t xdr_noleggi ();
extern bool_t xdr_input_elimina_sci ();
extern bool_t xdr_input_noleggia_sci ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NOLEGGIASCI_H_RPCGEN */
