/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RENTACAR_H_RPCGEN
#define _RENTACAR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define FILE_NAME_DIM 50
#define STRING_DIM 50
#define PATENTE_DIM 6
#define MAX_PRENOTAZIONI 100
#define MAX_PRENOTAZIONI_CERCATE 6

struct prenotazione {
	char targa[STRING_DIM];
	char patente[PATENTE_DIM];
	char tipo[STRING_DIM];
	char direttorio_img[FILE_NAME_DIM];
};
typedef struct prenotazione prenotazione;

struct prenotazioni {
	prenotazione entry[MAX_PRENOTAZIONI];
};
typedef struct prenotazioni prenotazioni;

struct tipoVeicolo {
	char tipo[STRING_DIM];
};
typedef struct tipoVeicolo tipoVeicolo;

struct prenotazioni_cercate {
	prenotazione entry[MAX_PRENOTAZIONI_CERCATE];
};
typedef struct prenotazioni_cercate prenotazioni_cercate;

struct input_aggiorna_licenza {
	char targa[STRING_DIM];
	char patente_nuova[PATENTE_DIM];
};
typedef struct input_aggiorna_licenza input_aggiorna_licenza;

#define RENT_A_CAR 0x20000013
#define RENT_A_CAR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA_PRENOTAZIONI 1
extern  prenotazioni_cercate * visualizza_prenotazioni_1(tipoVeicolo *, CLIENT *);
extern  prenotazioni_cercate * visualizza_prenotazioni_1_svc(tipoVeicolo *, struct svc_req *);
#define AGGIORNA_LICENZA 2
extern  int * aggiorna_licenza_1(input_aggiorna_licenza *, CLIENT *);
extern  int * aggiorna_licenza_1_svc(input_aggiorna_licenza *, struct svc_req *);
extern int rent_a_car_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA_PRENOTAZIONI 1
extern  prenotazioni_cercate * visualizza_prenotazioni_1();
extern  prenotazioni_cercate * visualizza_prenotazioni_1_svc();
#define AGGIORNA_LICENZA 2
extern  int * aggiorna_licenza_1();
extern  int * aggiorna_licenza_1_svc();
extern int rent_a_car_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_prenotazione (XDR *, prenotazione*);
extern  bool_t xdr_prenotazioni (XDR *, prenotazioni*);
extern  bool_t xdr_tipoVeicolo (XDR *, tipoVeicolo*);
extern  bool_t xdr_prenotazioni_cercate (XDR *, prenotazioni_cercate*);
extern  bool_t xdr_input_aggiorna_licenza (XDR *, input_aggiorna_licenza*);

#else /* K&R C */
extern bool_t xdr_prenotazione ();
extern bool_t xdr_prenotazioni ();
extern bool_t xdr_tipoVeicolo ();
extern bool_t xdr_prenotazioni_cercate ();
extern bool_t xdr_input_aggiorna_licenza ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RENTACAR_H_RPCGEN */
