/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RentACar.h"

bool_t
xdr_prenotazione (XDR *xdrs, prenotazione *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->targa, STRING_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->patente, PATENTE_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, STRING_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->direttorio_img, FILE_NAME_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_prenotazioni (XDR *xdrs, prenotazioni *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->entry, MAX_PRENOTAZIONI,
		sizeof (prenotazione), (xdrproc_t) xdr_prenotazione))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tipoVeicolo (XDR *xdrs, tipoVeicolo *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, STRING_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_prenotazioni_cercate (XDR *xdrs, prenotazioni_cercate *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->entry, MAX_PRENOTAZIONI_CERCATE,
		sizeof (prenotazione), (xdrproc_t) xdr_prenotazione))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input_aggiorna_licenza (XDR *xdrs, input_aggiorna_licenza *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->targa, STRING_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->patente_nuova, PATENTE_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
