/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file.h"

bool_t
xdr_nome_file (XDR *xdrs, nome_file *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, FILE_NAME_DIM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output_lista_sottodirettori (XDR *xdrs, output_lista_sottodirettori *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->sottodirettori, MAX_SOTTODIRETTORI,
		sizeof (nome_file), (xdrproc_t) xdr_nome_file))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valido))
		 return FALSE;
	return TRUE;
}
