/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_H_RPCGEN
#define _FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define FILE_NAME_DIM 256
#define MAX_SOTTODIRETTORI 6

struct nome_file {
	char nome[FILE_NAME_DIM];
};
typedef struct nome_file nome_file;

struct output_lista_sottodirettori {
	nome_file sottodirettori[MAX_SOTTODIRETTORI];
	int valido;
};
typedef struct output_lista_sottodirettori output_lista_sottodirettori;

#define FILES 0x20000013
#define FILES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ELIMINA_OCCORRENZE 1
extern  int * elimina_occorrenze_1(nome_file *, CLIENT *);
extern  int * elimina_occorrenze_1_svc(nome_file *, struct svc_req *);
#define LISTA_SOTTODIRETTORI 2
extern  output_lista_sottodirettori * lista_sottodirettori_1(nome_file *, CLIENT *);
extern  output_lista_sottodirettori * lista_sottodirettori_1_svc(nome_file *, struct svc_req *);
extern int files_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ELIMINA_OCCORRENZE 1
extern  int * elimina_occorrenze_1();
extern  int * elimina_occorrenze_1_svc();
#define LISTA_SOTTODIRETTORI 2
extern  output_lista_sottodirettori * lista_sottodirettori_1();
extern  output_lista_sottodirettori * lista_sottodirettori_1_svc();
extern int files_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nome_file (XDR *, nome_file*);
extern  bool_t xdr_output_lista_sottodirettori (XDR *, output_lista_sottodirettori*);

#else /* K&R C */
extern bool_t xdr_nome_file ();
extern bool_t xdr_output_lista_sottodirettori ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_H_RPCGEN */
